"""
브리핑 보고서 생성 모듈
Markdown 형식의 데일리 브리핑 보고서를 생성합니다.
"""
import sys
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional

# Windows UTF-8 설정
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import REPORT_TITLE, get_today_output_dir


def generate_briefing_report(
    videos: List[Dict],
    notebooklm_analysis: Optional[str] = None,
) -> Path:
    """
    데일리 브리핑 Markdown 보고서를 생성합니다.

    Args:
        videos: 트랜스크립트가 포함된 영상 리스트
        notebooklm_analysis: NotebookLM의 분석 결과 (선택)

    Returns:
        생성된 보고서 파일 경로
    """
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")
    output_dir = get_today_output_dir()
    report_path = output_dir / f"{date_str}-briefing.md"

    lines = []

    # 헤더
    lines.append(f"# 📋 {REPORT_TITLE}")
    lines.append(f"**날짜:** {date_str} | **생성 시각:** {time_str}")
    lines.append(f"**수집 영상:** {len(videos)}개\n")
    lines.append("---\n")

    # NotebookLM 분석 결과
    if notebooklm_analysis:
        lines.append("## 🤖 AI 종합 분석 (NotebookLM)\n")
        lines.append(notebooklm_analysis)
        lines.append("\n---\n")

    # 채널별 영상 그룹핑
    channels = {}
    for v in videos:
        ch = v.get("channel_name", "Unknown")
        if ch not in channels:
            channels[ch] = []
        channels[ch].append(v)

    # 영상 요약
    lines.append("## 📹 채널별 영상 요약\n")

    for channel_name, channel_videos in channels.items():
        lines.append(f"### 📺 {channel_name}\n")

        for v in channel_videos:
            title = v.get("title", "제목 없음")
            url = v.get("url", "")
            published = v.get("published", "")
            transcript = v.get("transcript", "")

            lines.append(f"#### [{title}]({url})\n")
            if published:
                lines.append(f"- **게시일:** {published}")
            if transcript:
                lines.append(f"- **자막 길이:** {len(transcript):,}자 ({v.get('transcript_language', '?')})")

                # 트랜스크립트에서 핵심 내용 추출 (처음 300자)
                preview = transcript[:300].replace("\n", " ")
                lines.append(f"- **미리보기:** {preview}...")
            lines.append("")

    # 통계
    lines.append("---\n")
    lines.append("## 📊 수집 통계\n")
    lines.append(f"| 항목 | 값 |")
    lines.append(f"|------|------|")
    lines.append(f"| 채널 수 | {len(channels)} |")
    lines.append(f"| 총 영상 수 | {len(videos)} |")

    total_transcript_chars = sum(len(v.get("transcript", "")) for v in videos)
    lines.append(f"| 총 자막 길이 | {total_transcript_chars:,}자 |")

    transcript_success = sum(1 for v in videos if v.get("transcript"))
    lines.append(f"| 자막 추출 성공 | {transcript_success}/{len(videos)} |")
    lines.append("")

    # 푸터
    lines.append("---\n")
    lines.append(f"*Generated by YouTube Daily Briefing Agent*")
    lines.append(f"*{now.strftime('%Y-%m-%d %H:%M:%S')}*")

    # 파일 저장
    content = "\n".join(lines)
    report_path.write_text(content, encoding="utf-8")

    print(f"📄 보고서 생성 완료: {report_path}")
    return report_path
